### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by Dean-Coakley** [davej/CorkJS#5]
Hey,

A few days ago I decided to go over my commit messages and try improve them. I see that using "Add" instead of "Added" is greatly preferred on most projects.

So if I remember correctly I tried
```
git rebase -i HEAD~9
git push -f
```

I then set "reword" on most of my commits and I think one or two of yours. But when I pushed it still counts as new commits it seems? I thought rebase reword would 'rewrite history' as such? Should I still continue with this change? Or should I just drop all changes and rebase back to your master?

Sidenote: Any particular ideas for changes? I'm thinking I will add a counter for number of people attending. The upcoming tag could be 'greyed out' if it's previous?

 I was also thinking of using something to remove css rules that are not being used. I used Uncss before. But I think webpack does this too? Probably in a better way? Or is that change stupid on such a small project. (Still might be good to learn for me - If there's anything difficult to webpack)

Sorry for the long issue.

**Comment by davej** [comment]
Hey Dean,

It's rarely a good idea to rewrite history once it's been pushed as it makes thinks very messy for everybody else who has cloned the repo. I don't know for sure but I imagine Github creates new commits to so that it is non-destructive and doesn't mess things up for everyone else. You can google around to read more about why this is a bad idea but here is something from the docs: https://www.kernel.org/pub/software/scm/git/docs/user-manual.html#problems-With-rewriting-history

> Sidenote: Any particular ideas for changes? I'm thinking I will add a counter for number of people attending. The upcoming tag could be 'greyed out' if it's previous?

Sounds good to me :) Can't think of much else right now, prehaps a map showing the location? Or aggregate all tweets with the CorkJS hashtag?

> I was also thinking of using something to remove css rules that are not being used. I used Uncss before. But I think webpack does this too? Probably in a better way? Or is that change stupid on such a small project. (Still might be good to learn for me - If there's anything difficult to webpack)

I think keep it simple for now. If it's too complicated then it might get in the way of other people contributing.

Thanks! :)

**Comment by Dean-Coakley** [comment]
Cool, I've rebased so. Yeah it definitely seems like a bad idea. But when I tried to contribute to NodeJs they asked me to do it! They would only accept my pull request if I dropped/reworded/merged all my commits so that only one commit remained.

Not related to that, but I assume` git commit --amend `is acceptable/fine to do? Or is it only alright to do if I haven't pushed yet?

I'll get working on some of these changes sometime this week.

Not related again: Trying to get a (hopefully) working bugfix into Webpack but again they won't merge without me adding a test. Any ideas on how to do this? Not very familiar with Webpack or even the bug I tried to fix.

**Comment by davej** [comment]
Yeah, it's ok to rewrite history if it's on a PR or a branch that only you are using. It only becomes a problem when it's a branch that multiple people are working on. That goes for `amend` too.

Sorry I'm not much help with the webpack test.
